In [1]:
import numpy as np

arr_1d = np.array([1, 2, 3, 4])
print(arr_1d)

[1 2 3 4]


In [2]:
#creation of 2d array
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print(arr_2d)

[[1 2 3]
 [4 5 6]]


In [3]:
#ones function
np.ones((4,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [4]:
#zeros function
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [5]:
#Array Properties: You can check the shape, size, and data type of an array:

print("Shape:", arr_2d.shape)  # Output: (2, 3)
print("Size:", arr_2d.size)    # Output: 6
print("Data type:", arr_2d.dtype)  # Output: int64 (or similar depending on your system)

Shape: (2, 3)
Size: 6
Data type: int32


In [6]:
#Basic Operations: NumPy allows for element-wise operations:

arr = np.array([1, 2, 3])
print(arr + 5)  # Adds 5 to each element
print(arr * 2)  # Multiplies each element by 2

[6 7 8]
[2 4 6]


In [7]:
#Array Slicing: You can slice arrays just like lists:

print(arr_1d[1:3])  # Output: [2, 3]
print(arr_2d[:, 1])  # Output: [2, 5] (second column)

[2 3]
[2 5]


In [8]:
#Mathematical Functions: NumPy provides a variety of mathematical functions:

arr = np.array([1, 2, 3])
print(np.mean(arr))  # Mean
print(np.sum(arr))   # Sum
print(np.std(arr))   # Standard deviation

2.0
6
0.816496580927726


In [9]:
#Reshaping Arrays: You can reshape arrays without changing their data:

reshaped_arr = arr_2d.reshape(3, 2)
print(reshaped_arr)

[[1 2]
 [3 4]
 [5 6]]


In [10]:
# Array Broadcasting: NumPy automatically expands the dimensions of arrays during arithmetic operations:

arr_3d = np.array([[1], [2], [3]])
print(arr_3d + np.array([1, 2, 3]))  # Adds each element of arr_3d with the 1D array

[[2 3 4]
 [3 4 5]
 [4 5 6]]


In [11]:
#Searching for elements in an array.

arr = np.array([10, 20, 30, 40, 50])
result = np.where(arr == 30)  # Find index where value is 30
print(result)

(array([2], dtype=int64),)


In [12]:
#Sorting elements in an array.

arr = np.array([3, 1, 2, 4, 5])
sorted_arr = np.sort(arr)
print(sorted_arr)

[1 2 3 4 5]


In [13]:
#Splitting an array into multiple sub-arrays.

arr = np.array([1, 2, 3, 4, 5, 6])
split_arr = np.split(arr, 3)  # Splits into 3 equal parts
print(split_arr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [14]:
#Stacking arrays along a new axis.

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
stacked = np.stack((arr1, arr2), axis=0)  # Stack along first axis (rows)
print(stacked)

[[1 2 3]
 [4 5 6]]


In [15]:
#Creating a view or a copy of an array.

arr = np.array([1, 2, 3, 4])
view = arr.view()  # View of the original array
copy = arr.copy()  # Independent copy of the array
view[0] = 10
print(arr)  # Output: [10, 2, 3, 4]  # View changes the original
print(copy)

[10  2  3  4]
[1 2 3 4]


In [16]:
#Iterating over the elements of an array.

arr = np.array([1, 2, 3, 4, 5])
for elem in arr:
    print(elem)

1
2
3
4
5


In [17]:
#Accessing elements or subarrays using specific indices.

arr = np.array([10, 20, 30, 40, 50])
print(arr[2])

30


In [22]:
#filtering/Selecting elements based on a condition.

arr = np.array([10, 20, 30, 40, 50])
filtered = arr[arr > 30]  # Select elements greater than 30
print(filtered)

[40 50]


In [23]:
#Concatenating/Joining two or more arrays along an axis.

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
concatenated = np.concatenate((arr1, arr2))  # Concatenate along the first axis
print(concatenated)

[1 2 3 4 5 6]


In [20]:
a=np.array([[1,2,3,4],[4, 5, 6,0]])
print(a.shape)

(2, 4)


In [24]:
# 2x2 matrix shape/size
arr = np.array([[1, 2], [3, 4]])  
print(arr)
print(arr.shape)
print(arr.size)

[[1 2]
 [3 4]]
(2, 2)
4


In [25]:
# 3-d array shape/size
arr=np.array([[[1,4,5,8],[1,2,5,9],[0,8,4,5]],[[1,4,5,8],[1,2,5,9],[0,8,4,5]]])
print(arr.shape)

(2, 3, 4)


In [26]:
# Slice from index 2 to index 5 (exclusive)

arr = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])

sliced_arr = arr[2:5]
print("Sliced Array (from index 2 to 5):")
print(sliced_arr)

Sliced Array (from index 2 to 5):
[30 40 50]


In [27]:
# Slice with a step size of 2

sliced_arr_step = arr[::2]
print("Sliced Array with step size 2:")
print(sliced_arr_step)

Sliced Array with step size 2:
[10 30 50 70 90]


In [28]:
# Create a 2D NumPy array (5x5 matrix)
arr_2d = np.array([
    [1, 2, 3, 4, 5],
    [6, 7, 8, 9, 10],
    [11, 12, 13, 14, 15],
    [16, 17, 18, 19, 20],
    [21, 22, 23, 24, 25]
])

print("Original 2D Array:")
print(arr_2d)

Original 2D Array:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [29]:
# Slice rows 1 to 3 (exclusive), and columns 1 to 4 (exclusive)

sliced_2d = arr_2d[1:4, 1:4]
print("Sliced 2D Array (rows 1 to 3 and columns 1 to 4):")
print(sliced_2d)

Sliced 2D Array (rows 1 to 3 and columns 1 to 4):
[[ 7  8  9]
 [12 13 14]
 [17 18 19]]
